# This repository uses nbdev's pre-commit hooks. For more information see:
# https://nbdev.fast.ai/tutorials/pre_commit.html
repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean